name: Build and Publish Greengrass Component

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} > aws_access_key_id
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} > aws_secret_access_key
          chmod 400 aws_*

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli

      - name: Install Greengrass Development Kit (GDK)
        run: |
          sudo apt-get install -y curl
          curl -s https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip > greengrass-nucleus-latest.zip
          sudo apt-get install -y unzip
          unzip greengrass-nucleus-latest.zip
          sudo ./greengrass-nucleus-latest/install.sh

      - name: Build and publish Greengrass Component
        run: |
          gdk component build
          gdk component publish --bucket sivertheisholt
